AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - 'node_modules/**/**'
    - db/schema.rb
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Exclude:
    - 'test/**/**'
Metrics/MethodLength:
  Exclude:
    - 'db/**/**'
Layout/LineLength:
  Exclude:
    - 'config/initializers/**'
